[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[env]
ESP_LOG = "info"

[build]
rustflags = [
  # Required To Obtain Backtraces (e.g. When Using the 'esp-backtrace' Crate).
  # NOTE: May Negatively Impact Performance of Produced Code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
