# Copyright (c) 2026 MurlokVR Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "murlokvr-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
display-info = "0.5"
json = "0.12"
nalgebra = "0.35"
serialport = "4.9"

[dependencies.windows-sys]
version = ">=0.59, <=0.61"
features = ["Win32_Security", "Win32_System_Memory"]
